services:
  ui:
    build: ./zizza-ui
    container_name: ui
    ports:
      - "3000:8080"
    volumes:
      - ui-data:/app/backend/data
    restart: always
    networks:
      - znet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ZIZZA_BLOCKCHAIN_INTENTS_SERVER_HOST=blockchain-intents-server
      - CORS_ALLOW_ORIGIN=https://zizza.xyz,http://localhost


  blockchain-intents-server:
    build: ./zizza-blockchain-intents-server
    container_name: blockchain-intents-server
    restart: always
    networks:
      - znet
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ui-data:

networks:
  znet:
